### ISSUE TITLE
Contradict with black

### ISSUE THREAD

**Issue by mariostg** [asottile/reorder-python-imports#375]
In my pre-commit yml file, I use both black and reorder-python-import.  Black keeps placing a space between the import and  the last """ while reorder-python-import removes it which yields to both hooks failing.  It does not matter in which order I place the hooks in the pre-commit config file.

Typical case file:
```
"""
WSGI config for main project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "main.settings")

application = get_wsgi_application()

```

Pre-commit hooks:
```
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
    args:
    - --py311-plus
 
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: "24.3.0"
    hooks:
    - id: black
```
